### ISSUE TITLE
'name' is reserved: cant use 'name' as a column name

### ISSUE THREAD

**Issue by BEN00262** [elliotchance/vsql#103]
Hi was trying to create a table with 'name' as a column but got a crash, looking into the lexer i realized that name is marked as a keyword. Is this by design?
```bash
vsql> create table person (name character varying(100));
# cli execution error: vsql.SQLState42601: syntax error: near "NAME"
```

**Comment by elliotchance** [comment]
That being said, I think the error message should be clearer with a suggestion so it's not so bizarre:

`syntax error: near "NAME" (using key word as identifier?)`

**Comment by elliotchance** [comment]
@BEN00262 Turns out you can use non reserved words as identifiers: https://github.com/elliotchance/vsql/releases/tag/v0.24.1
