### ISSUE TITLE
PG server!

### ISSUE THREAD

**Issue by ichson** [elliotchance/vsql#141]
Can you please provide an example on how to connect to the postgres server within the code itself as i plan for multiple people to use the program and the docs only said how to do it from command line.

**Comment by elliotchance** [comment]
@ichson https://vsql.readthedocs.io/en/latest/postgresql-clients.html

**Comment by ichson** [comment]
It shows the connection details but not how to specifically connect? do i just make a struct with .connect?

**Comment by elliotchance** [comment]
You can start the server with the CLI: https://vsql.readthedocs.io/en/latest/cli.html#server

Then connect to it with a PostgreSQL compatible client.

**Comment by ichson** [comment]
my application is designed for multi-user access, considering that the documentation only provides instructions on establishing a connection from the command line would that mean every one who uses my program has to connect to the server via to CLI? and then couldnt breach the db?

**Comment by elliotchance** [comment]
We discussed this offline. Closing.
